# Generated by Django 5.0.6 on 2024-09-30 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='first_sentence',
            new_name='content',
        ),
    ]
